"use client";

import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function ResearchPage() {
  return (
    <div className="min-h-screen bg-[#0B1026]">
      <header className="sticky top-0 z-10 border-b border-[#6E7BAA]/20 bg-[#0B1026] px-6 py-4">
        <div className="mx-auto max-w-4xl">
          <Link
            href="/"
            className="flex items-center gap-2 text-gray-300 transition-colors hover:text-white"
          >
            <ArrowLeft className="h-5 w-5" />
            <span>Back to Explorer</span>
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-12">
        <h1 className="mb-3 text-4xl font-bold text-[#4BE37A]">
          Further Research
        </h1>
        <p className="mb-8 text-gray-300">
          Explore the key factors that determine whether a planet can support
          life as we know it.
        </p>

        <div className="space-y-4">
          <div className="rounded-lg border border-[#6E7BAA]/20 bg-[#1A2142] px-6">
            <details>
              <summary className="cursor-pointer py-4 text-white transition-colors hover:text-[#4BE37A]">
                Magnetospheres: Shielding from Radiation
              </summary>
              <div className="space-y-3 pb-4 text-gray-300">
                <p>
                  A magnetosphere is a magnetic field that surrounds a planet,
                  generated by the motion of molten metals in its core. This
                  magnetic shield deflects harmful solar wind and cosmic
                  radiation that would otherwise strip away a planet&apos;s
                  atmosphere and bombard its surface with dangerous particles.
                </p>
                <p>
                  Earth&apos;s magnetosphere protects life by preventing
                  atmospheric erosion and reducing radiation levels at the
                  surface. Planets without strong magnetic fields, like Mars,
                  have lost most of their atmospheres over time, making them
                  less hospitable to life.
                </p>
                <p className="text-sm italic text-gray-400">
                  Key point: A strong magnetosphere is crucial for maintaining a
                  stable atmosphere and protecting potential life from
                  radiation.
                </p>
              </div>
            </details>
          </div>
        </div>

        <div className="mt-12 border-t border-[#6E7BAA]/20 pt-8">
          <Link
            href="/"
            className="inline-flex items-center gap-2 rounded-lg bg-[#4BE37A] px-6 py-3 font-semibold text-[#0B1026] transition-colors hover:bg-[#3BC366]"
          >
            Return to Exoplanet Explorer
          </Link>
        </div>
      </main>
    </div>
  );
}

